import ArticleLine from "./index.jsx";

const articleWithImage = {
  updated_at: "1673383611",
  created_at: "1673220215",
  data: {
    charset: "utf8",
    ogTitle: "Meet the YC Summer 2022 Batch | Y Combinator",
    dateMethod: "2022-09-07",
    description:
      "For the Summer 2022 batch, we received 19,000 applications from founders around the world and funded 240. Today, these founders will present their companies to an invite-only audience of investors at our 35th Demo Day. Here’s what we saw in the S22 batch.",
    source: {
      created_at: "",
      id: "YCOMBINATOR",
      data: {
        sourceUrl: "ycombinator.com",
        description: "",
        sourceImage: "ycombinator.jpg",
        sourceName: "YCombinator",
      },
      type: "SOURCE",
      sourceType: "hard",
    },
    title: "Meet the YC Summer 2022 Batch | Y Combinator",
    type: "website",
    ogType: "website",
    twitterCard: "summary_large_image",
    requestUrl:
      "https://www.ycombinator.com/blog/meet-the-yc-summer-2022-batch/",
    ogSiteName: "Y Combinator",
    image: {
      width: null,
      type: "png",
      url: "https://www.ycombinator.com/blog/content/images/2022/09/ycombinator_announcement_1200x603-1.png",
      height: null,
    },
    twitterSite: "@ycombinator",
    userDescription: "",
    eURL: "https://www.ycombinator.com/blog/meet-the-yc-summer-2022-batch/",
    favicon:
      "/assets/ycdc/favicon-c8a914eeeba9fe6f7a863b35608b55aeedd7c1ff409c97b9ecb96b7a6c278d70.ico",
    twitterImage: {
      alt: null,
      width: null,
      url: "https://www.ycombinator.com/blog/content/images/2022/09/ycombinator_announcement_1200x603-1.png",
      height: null,
    },
    cumulatives: [{ value: "240", text: "Funded Companies" }],
    ogDescription:
      "For the Summer 2022 batch, we received 19,000 applications from founders around the world and funded 240. Today, these founders will present their companies to an invite-only audience of investors at our 35th Demo Day. Here’s what we saw in the S22 batch.",
    ogImage: {
      width: null,
      type: "png",
      url: "https://www.ycombinator.com/blog/content/images/2022/09/ycombinator_announcement_1200x603-1.png",
      height: null,
    },
    ogLocale: "en_US",
    url: "https://www.ycombinator.com/blog/meet-the-yc-summer-2022-batch",
    site_name: "Y Combinator",
    userPoints: ["240 Companies were funded in this cycle"],
    success: true,
    articleDate: "2023-01-08T23:21:03.738Z",
    ogUrl: "https://www.ycombinator.com/blog/meet-the-yc-summer-2022-batch",
  },
  SK: "ARTICLE#01GP9V4MZBDCEZSCMH54JBZEFX",
  PK: "PTAG#01GP4MTAZ5VD19GR60F031YGR7",
  id: "01GP9V4MZBDCEZSCMH54JBZEFX",
  sourceId: "YCOMBINATOR",
  creatorId: null,
  itemDate: "2022-09-07",
  parent_tag_id: "01GP4MTAZ5VD19GR60F031YGR7",
  type: "ARTICLE",
};

const article = {
  updated_at: "1673383687",
  created_at: "1673278236",
  data: {
    charset: "utf8",
    ogTitle: "YC Winter 2018 Stats | Y Combinator",
    dateMethod: "2018-03-19",
    description:
      "Today is Y Combinator’s 26th Demo Day.\n\n141 companies will be presenting over the next two days — which makes this the\nlargest Demo Day in YC’s 13 years. You can read more about the companies\npresenting here [https://blog.ycombinator.com/14-companies-from-yc-winter-2018/]\n, here [https://blog.ycombinator.com/13-companies-from-yc-winter-2018/], here\n[https://blog.ycombinator.com/10-companies-from-yc-winter-2018/], here\n[https://blog.ycombinator.com/8-companies-from-yc-winter-2018/], here\n[https:/",
    source: {
      created_at: "",
      id: "YCOMBINATOR",
      data: {
        sourceUrl: "ycombinator.com",
        description: "",
        sourceImage: "ycombinator.jpg",
        sourceName: "YCombinator",
      },
      type: "SOURCE",
      sourceType: "hard",
    },
    title: "YC Winter 2018 Stats | Y Combinator",
    type: "website",
    ogType: "website",
    twitterCard: "summary_large_image",
    requestUrl: "https://www.ycombinator.com/blog/yc-winter-2018-stats",
    ogSiteName: "Y Combinator",
    twitterSite: "@ycombinator",
    userDescription: "",
    eURL: "https://www.ycombinator.com/blog/yc-winter-2018-stats",
    favicon:
      "/assets/ycdc/favicon-c8a914eeeba9fe6f7a863b35608b55aeedd7c1ff409c97b9ecb96b7a6c278d70.ico",
    twitterImage: { alt: null, width: null, height: null },
    cumulatives: [{ value: "141", text: "Funded Companies" }],
    ogDescription:
      "Today is Y Combinator’s 26th Demo Day.\n\n141 companies will be presenting over the next two days — which makes this the\nlargest Demo Day in YC’s 13 years. You can read more about the companies\npresenting here [https://blog.ycombinator.com/14-companies-from-yc-winter-2018/]\n, here [https://blog.ycombinator.com/13-companies-from-yc-winter-2018/], here\n[https://blog.ycombinator.com/10-companies-from-yc-winter-2018/], here\n[https://blog.ycombinator.com/8-companies-from-yc-winter-2018/], here\n[https:/",
    ogLocale: "en_US",
    url: "https://www.ycombinator.com/blog/yc-winter-2018-stats",
    site_name: "Y Combinator",
    userPoints: ["Winter 2018 Batch", "141 Companies were funded"],
    success: true,
    articleDate: "2023-01-09T15:30:00.785Z",
    ogUrl: "https://www.ycombinator.com/blog/yc-winter-2018-stats",
  },
  SK: "ARTICLE#01GPBJFA8KVEX3R8T116AEF38T",
  PK: "PTAG#01GP4MTAZ5VD19GR60F031YGR7",
  id: "01GPBJFA8KVEX3R8T116AEF38T",
  sourceId: "YCOMBINATOR",
  creatorId: null,
  itemDate: "2018-03-19",
  parent_tag_id: "01GP4MTAZ5VD19GR60F031YGR7",
  type: "ARTICLE",
};

const parentTag = {
  created_at: "1673045814",
  imports: 0,
  followers: 0,
  creatorEmail: "jfoxworth@cadwolf.com",
  updated_at: "1680540586",
  data: {
    userPoints: [],
    tagTree: [
      {
        imports: 0,
        data: {
          userPoints: [],
          tagTree: [],
          tagColor: "#898989",
          articlesListLimit: 5,
          cumulatives: [],
          description:
            "This tag includes stories related to technology, but not science. This can be crypto information, new apple devices, AI, new software advancements, and similar items.",
          articlesList: [],
          tagName: "Technology",
          userName: "TheWolf",
          textColor: "#FFFFFF",
        },
        creatorEmail: "jfoxworth@cadwolf.com",
        creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
        created_at: "1672798519",
        type: "TAG",
        followers: 0,
        updated_at: 0,
        SK: "",
        parent_tag_id: "0",
        PK: "",
        id: "01GNX8ZGFM2P9BZX6DTA610ZF6",
        articlesList: [],
        embeds: 0,
      },
      {
        imports: 0,
        data: {
          userPoints: [],
          tagTree: [
            {
              imports: 0,
              data: {
                userPoints: [],
                tagTree: [],
                tagColor: "#898989",
                articlesListLimit: 5,
                cumulatives: [],
                description:
                  "This tag includes stories related to technology, but not science. This can be crypto information, new apple devices, AI, new software advancements, and similar items.",
                articlesList: [],
                tagName: "Technology",
                userName: "TheWolf",
                textColor: "#FFFFFF",
              },
              creatorEmail: "jfoxworth@cadwolf.com",
              creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
              created_at: "1672798519",
              type: "TAG",
              followers: 0,
              updated_at: 0,
              SK: "",
              parent_tag_id: "0",
              PK: "",
              id: "01GNX8ZGFM2P9BZX6DTA610ZF6",
              articlesList: [],
              embeds: 0,
            },
          ],
          tagColor: "#239f31",
          cumulatives: [],
          description:
            "This tag holds all information related to startups, incubators, accelerators, and similar organizations and events.",
          articlesList: [],
          tagName: "Startups",
          userName: "TheWolf",
          articleListLimit: 5,
          textColor: "#FFFFFF",
        },
        creatorEmail: "jfoxworth@cadwolf.com",
        creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
        created_at: "1672975460",
        cumulatives: [],
        type: "TAG",
        followers: 0,
        tagTree: [],
        updated_at: "1672975475",
        SK: "TAG#01GP2HQ9PB9TDYDFNPVRHEM973",
        parent_tag_id: "01GNX8ZGFM2P9BZX6DTA610ZF6",
        PK: "PTAG#01GNX8ZGFM2P9BZX6DTA610ZF6",
        id: "01GP2HQ9PB9TDYDFNPVRHEM973",
        articlesList: [],
        embeds: 0,
      },
      {
        imports: 0,
        data: {
          userPoints: [],
          tagTree: [
            {
              imports: 0,
              data: {
                userPoints: [],
                tagTree: [],
                tagColor: "#898989",
                articlesListLimit: 5,
                cumulatives: [],
                description:
                  "This tag includes stories related to technology, but not science. This can be crypto information, new apple devices, AI, new software advancements, and similar items.",
                articlesList: [],
                tagName: "Technology",
                userName: "TheWolf",
                textColor: "#FFFFFF",
              },
              creatorEmail: "jfoxworth@cadwolf.com",
              creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
              created_at: "1672798519",
              type: "TAG",
              followers: 0,
              updated_at: 0,
              SK: "",
              parent_tag_id: "0",
              PK: "",
              id: "01GNX8ZGFM2P9BZX6DTA610ZF6",
              articlesList: [],
              embeds: 0,
            },
            {
              imports: 0,
              data: {
                userPoints: [],
                tagTree: [
                  {
                    imports: 0,
                    data: {
                      userPoints: [],
                      tagTree: [],
                      tagColor: "#898989",
                      articlesListLimit: 5,
                      cumulatives: [],
                      description:
                        "This tag includes stories related to technology, but not science. This can be crypto information, new apple devices, AI, new software advancements, and similar items.",
                      articlesList: [],
                      tagName: "Technology",
                      userName: "TheWolf",
                      textColor: "#FFFFFF",
                    },
                    creatorEmail: "jfoxworth@cadwolf.com",
                    creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
                    created_at: "1672798519",
                    type: "TAG",
                    followers: 0,
                    updated_at: 0,
                    SK: "",
                    parent_tag_id: "0",
                    PK: "",
                    id: "01GNX8ZGFM2P9BZX6DTA610ZF6",
                    articlesList: [],
                    embeds: 0,
                  },
                ],
                tagColor: "#239f31",
                cumulatives: [],
                description:
                  "This tag holds all information related to startups, incubators, accelerators, and similar organizations and events.",
                articlesList: [],
                tagName: "Startups",
                userName: "TheWolf",
                articleListLimit: 5,
                textColor: "#FFFFFF",
              },
              creatorEmail: "jfoxworth@cadwolf.com",
              creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
              created_at: "1672975460",
              cumulatives: [],
              type: "TAG",
              followers: 0,
              tagTree: [],
              updated_at: "1672975475",
              SK: "TAG#01GP2HQ9PB9TDYDFNPVRHEM973",
              parent_tag_id: "01GNX8ZGFM2P9BZX6DTA610ZF6",
              PK: "PTAG#01GNX8ZGFM2P9BZX6DTA610ZF6",
              id: "01GP2HQ9PB9TDYDFNPVRHEM973",
              articlesList: [],
              embeds: 0,
            },
          ],
          tagColor: "#a4193b",
          cumulatives: [],
          description:
            '"Incubators" or "accelerators" are organizations that fund and/or assist startup companies. Tags are present for the larger accelerators as well as information relating to overall startups.',
          articlesList: [],
          tagName: "Incubators / Accelerators",
          userName: "TheWolf",
          articleListLimit: 5,
          textColor: "#FFFFFF",
        },
        creatorEmail: "jfoxworth@cadwolf.com",
        creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
        created_at: "1672975876",
        cumulatives: [],
        type: "TAG",
        followers: 0,
        tagTree: [],
        updated_at: "1675791013",
        SK: "TAG#01GP2J40RYCC9KW416BSPH8X88",
        parent_tag_id: "01GP2HQ9PB9TDYDFNPVRHEM973",
        PK: "PTAG#01GP2HQ9PB9TDYDFNPVRHEM973",
        id: "01GP2J40RYCC9KW416BSPH8X88",
        articlesList: [],
        embeds: 0,
      },
      {
        imports: 0,
        data: {
          userPoints: [],
          tagTree: [
            {
              imports: 0,
              data: {
                userPoints: [],
                tagTree: [],
                tagColor: "#898989",
                articlesListLimit: 5,
                cumulatives: [],
                description:
                  "This tag includes stories related to technology, but not science. This can be crypto information, new apple devices, AI, new software advancements, and similar items.",
                articlesList: [],
                tagName: "Technology",
                userName: "TheWolf",
                textColor: "#FFFFFF",
              },
              creatorEmail: "jfoxworth@cadwolf.com",
              creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
              created_at: "1672798519",
              type: "TAG",
              followers: 0,
              updated_at: 0,
              SK: "",
              parent_tag_id: "0",
              PK: "",
              id: "01GNX8ZGFM2P9BZX6DTA610ZF6",
              articlesList: [],
              embeds: 0,
            },
            {
              imports: 0,
              data: {
                userPoints: [],
                tagTree: [
                  {
                    imports: 0,
                    data: {
                      userPoints: [],
                      tagTree: [],
                      tagColor: "#898989",
                      articlesListLimit: 5,
                      cumulatives: [],
                      description:
                        "This tag includes stories related to technology, but not science. This can be crypto information, new apple devices, AI, new software advancements, and similar items.",
                      articlesList: [],
                      tagName: "Technology",
                      userName: "TheWolf",
                      textColor: "#FFFFFF",
                    },
                    creatorEmail: "jfoxworth@cadwolf.com",
                    creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
                    created_at: "1672798519",
                    type: "TAG",
                    followers: 0,
                    updated_at: 0,
                    SK: "",
                    parent_tag_id: "0",
                    PK: "",
                    id: "01GNX8ZGFM2P9BZX6DTA610ZF6",
                    articlesList: [],
                    embeds: 0,
                  },
                ],
                tagColor: "#239f31",
                cumulatives: [],
                description:
                  "This tag holds all information related to startups, incubators, accelerators, and similar organizations and events.",
                articlesList: [],
                tagName: "Startups",
                userName: "TheWolf",
                articleListLimit: 5,
                textColor: "#FFFFFF",
              },
              creatorEmail: "jfoxworth@cadwolf.com",
              creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
              created_at: "1672975460",
              cumulatives: [],
              type: "TAG",
              followers: 0,
              tagTree: [],
              updated_at: "1672975475",
              SK: "TAG#01GP2HQ9PB9TDYDFNPVRHEM973",
              parent_tag_id: "01GNX8ZGFM2P9BZX6DTA610ZF6",
              PK: "PTAG#01GNX8ZGFM2P9BZX6DTA610ZF6",
              id: "01GP2HQ9PB9TDYDFNPVRHEM973",
              articlesList: [],
              embeds: 0,
            },
            {
              imports: 0,
              data: {
                userPoints: [],
                tagTree: [
                  {
                    imports: 0,
                    data: {
                      userPoints: [],
                      tagTree: [],
                      tagColor: "#898989",
                      articlesListLimit: 5,
                      cumulatives: [],
                      description:
                        "This tag includes stories related to technology, but not science. This can be crypto information, new apple devices, AI, new software advancements, and similar items.",
                      articlesList: [],
                      tagName: "Technology",
                      userName: "TheWolf",
                      textColor: "#FFFFFF",
                    },
                    creatorEmail: "jfoxworth@cadwolf.com",
                    creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
                    created_at: "1672798519",
                    type: "TAG",
                    followers: 0,
                    updated_at: 0,
                    SK: "",
                    parent_tag_id: "0",
                    PK: "",
                    id: "01GNX8ZGFM2P9BZX6DTA610ZF6",
                    articlesList: [],
                    embeds: 0,
                  },
                  {
                    imports: 0,
                    data: {
                      userPoints: [],
                      tagTree: [
                        {
                          imports: 0,
                          data: {
                            userPoints: [],
                            tagTree: [],
                            tagColor: "#898989",
                            articlesListLimit: 5,
                            cumulatives: [],
                            description:
                              "This tag includes stories related to technology, but not science. This can be crypto information, new apple devices, AI, new software advancements, and similar items.",
                            articlesList: [],
                            tagName: "Technology",
                            userName: "TheWolf",
                            textColor: "#FFFFFF",
                          },
                          creatorEmail: "jfoxworth@cadwolf.com",
                          creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
                          created_at: "1672798519",
                          type: "TAG",
                          followers: 0,
                          updated_at: 0,
                          SK: "",
                          parent_tag_id: "0",
                          PK: "",
                          id: "01GNX8ZGFM2P9BZX6DTA610ZF6",
                          articlesList: [],
                          embeds: 0,
                        },
                      ],
                      tagColor: "#239f31",
                      cumulatives: [],
                      description:
                        "This tag holds all information related to startups, incubators, accelerators, and similar organizations and events.",
                      articlesList: [],
                      tagName: "Startups",
                      userName: "TheWolf",
                      articleListLimit: 5,
                      textColor: "#FFFFFF",
                    },
                    creatorEmail: "jfoxworth@cadwolf.com",
                    creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
                    created_at: "1672975460",
                    cumulatives: [],
                    type: "TAG",
                    followers: 0,
                    tagTree: [],
                    updated_at: "1672975475",
                    SK: "TAG#01GP2HQ9PB9TDYDFNPVRHEM973",
                    parent_tag_id: "01GNX8ZGFM2P9BZX6DTA610ZF6",
                    PK: "PTAG#01GNX8ZGFM2P9BZX6DTA610ZF6",
                    id: "01GP2HQ9PB9TDYDFNPVRHEM973",
                    articlesList: [],
                    embeds: 0,
                  },
                ],
                tagColor: "#a4193b",
                cumulatives: [],
                description:
                  '"Incubators" or "accelerators" are organizations that fund and/or assist startup companies. Tags are present for the larger accelerators as well as information relating to overall startups.',
                articlesList: [],
                tagName: "Incubators / Accelerators",
                userName: "TheWolf",
                articleListLimit: 5,
                textColor: "#FFFFFF",
              },
              creatorEmail: "jfoxworth@cadwolf.com",
              creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
              created_at: "1672975876",
              cumulatives: [],
              type: "TAG",
              followers: 0,
              tagTree: [],
              updated_at: "1675791013",
              SK: "TAG#01GP2J40RYCC9KW416BSPH8X88",
              parent_tag_id: "01GP2HQ9PB9TDYDFNPVRHEM973",
              PK: "PTAG#01GP2HQ9PB9TDYDFNPVRHEM973",
              id: "01GP2J40RYCC9KW416BSPH8X88",
              articlesList: [],
              embeds: 0,
            },
          ],
          tagColor: "#f26625",
          cumulatives: [],
          description:
            "YCombinator is a startup factory/incubator that has batches twice a year where it funds numerous companies with a small round and provides mentorship and networking. This tag contains batch information as well as data related to individual companies.",
          articlesList: [],
          tagName: "YCombinator",
          userName: "TheWolf",
          articleListLimit: 5,
          textColor: "#FFFFFF",
        },
        creatorEmail: "jfoxworth@cadwolf.com",
        creatorId: null,
        created_at: "1672976167",
        cumulatives: [],
        type: "TAG",
        followers: 0,
        tagTree: [],
        updated_at: "1676841099",
        SK: "TAG#01GP2JCWM8CDN6GV06BAEJTNBY",
        parent_tag_id: "01GP2J40RYCC9KW416BSPH8X88",
        PK: "PTAG#01GP2J40RYCC9KW416BSPH8X88",
        id: "01GP2JCWM8CDN6GV06BAEJTNBY",
        articlesList: [],
        embeds: 0,
      },
    ],
    tagColor: "#14c838",
    cumulatives: [
      {
        text: "Funded Companies",
        color: "#188b26",
        value: 2382,
        cumId: "01GRHSXJ7XZAV75MHCTRSPZF29",
      },
    ],
    description:
      "This tag shows the story of the funding that YCombinator has issued over the course of its life. It adds up this information and graphs it out.",
    tagName: "Overall Funding",
    userName: "TheWolf",
    articleListLimit: 5,
    textColor: "#FFFFFF",
  },
  embeds: 0,
  SK: "TAG#01GP4MTAZ5VD19GR60F031YGR7",
  PK: "PTAG#01GP2JCWM8CDN6GV06BAEJTNBY",
  id: "01GP4MTAZ5VD19GR60F031YGR7",
  creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
  parent_tag_id: "01GP2JCWM8CDN6GV06BAEJTNBY",
  type: "TAG",
};

const Story = {
  title: "Compound/ArticleLine",
  component: ArticleLine,
};

const Template = (args) => <ArticleLine {...args} />;

export default {
  title: "Compound/ArticleLine",
  component: ArticleLine,
};

export const ArticleLineWithImage = Template.bind({});
ArticleLineWithImage.args = {
  article: articleWithImage,
  parentTag: parentTag,
};

export const ArticleLineNoImage = Template.bind({});
ArticleLineNoImage.args = {
  article: article,
  parentTag: parentTag,
};
