import Tag from "./index.jsx";
import { Container } from "react-bootstrap";

// More on how to set up stories at: https://storybook.js.org/docs/react/writing-stories/introduction
export default {
  title: "Simple/Tag",
  component: Tag,
  args: {
    tag: {
      created_at: "1672976167",
      imports: 0,
      followers: 0,
      creatorEmail: "jfoxworth@cadwolf.com",
      updated_at: "1676841099",
      data: {
        userPoints: [],
        tagTree: [
          {
            imports: 0,
            data: {
              userPoints: [],
              tagTree: [],
              tagColor: "#898989",
              articlesListLimit: 5,
              cumulatives: [],
              description:
                "This tag includes stories related to technology, but not science. This can be crypto information, new apple devices, AI, new software advancements, and similar items.",
              articlesList: [],
              tagName: "Technology",
              userName: "TheWolf",
              textColor: "#FFFFFF",
            },
            creatorEmail: "jfoxworth@cadwolf.com",
            creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
            created_at: "1672798519",
            type: "TAG",
            followers: 0,
            updated_at: 0,
            SK: "",
            parent_tag_id: "0",
            PK: "",
            id: "01GNX8ZGFM2P9BZX6DTA610ZF6",
            articlesList: [],
            embeds: 0,
          },
          {
            imports: 0,
            data: {
              userPoints: [],
              tagTree: [
                {
                  imports: 0,
                  data: {
                    userPoints: [],
                    tagTree: [],
                    tagColor: "#898989",
                    articlesListLimit: 5,
                    cumulatives: [],
                    description:
                      "This tag includes stories related to technology, but not science. This can be crypto information, new apple devices, AI, new software advancements, and similar items.",
                    articlesList: [],
                    tagName: "Technology",
                    userName: "TheWolf",
                    textColor: "#FFFFFF",
                  },
                  creatorEmail: "jfoxworth@cadwolf.com",
                  creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
                  created_at: "1672798519",
                  type: "TAG",
                  followers: 0,
                  updated_at: 0,
                  SK: "",
                  parent_tag_id: "0",
                  PK: "",
                  id: "01GNX8ZGFM2P9BZX6DTA610ZF6",
                  articlesList: [],
                  embeds: 0,
                },
              ],
              tagColor: "#239f31",
              cumulatives: [],
              description:
                "This tag holds all information related to startups, incubators, accelerators, and similar organizations and events.",
              articlesList: [],
              tagName: "Startups",
              userName: "TheWolf",
              articleListLimit: 5,
              textColor: "#FFFFFF",
            },
            creatorEmail: "jfoxworth@cadwolf.com",
            creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
            created_at: "1672975460",
            cumulatives: [],
            type: "TAG",
            followers: 0,
            tagTree: [],
            updated_at: "1672975475",
            SK: "TAG#01GP2HQ9PB9TDYDFNPVRHEM973",
            parent_tag_id: "01GNX8ZGFM2P9BZX6DTA610ZF6",
            PK: "PTAG#01GNX8ZGFM2P9BZX6DTA610ZF6",
            id: "01GP2HQ9PB9TDYDFNPVRHEM973",
            articlesList: [],
            embeds: 0,
          },
          {
            imports: 0,
            data: {
              userPoints: [],
              tagTree: [
                {
                  imports: 0,
                  data: {
                    userPoints: [],
                    tagTree: [],
                    tagColor: "#898989",
                    articlesListLimit: 5,
                    cumulatives: [],
                    description:
                      "This tag includes stories related to technology, but not science. This can be crypto information, new apple devices, AI, new software advancements, and similar items.",
                    articlesList: [],
                    tagName: "Technology",
                    userName: "TheWolf",
                    textColor: "#FFFFFF",
                  },
                  creatorEmail: "jfoxworth@cadwolf.com",
                  creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
                  created_at: "1672798519",
                  type: "TAG",
                  followers: 0,
                  updated_at: 0,
                  SK: "",
                  parent_tag_id: "0",
                  PK: "",
                  id: "01GNX8ZGFM2P9BZX6DTA610ZF6",
                  articlesList: [],
                  embeds: 0,
                },
                {
                  imports: 0,
                  data: {
                    userPoints: [],
                    tagTree: [
                      {
                        imports: 0,
                        data: {
                          userPoints: [],
                          tagTree: [],
                          tagColor: "#898989",
                          articlesListLimit: 5,
                          cumulatives: [],
                          description:
                            "This tag includes stories related to technology, but not science. This can be crypto information, new apple devices, AI, new software advancements, and similar items.",
                          articlesList: [],
                          tagName: "Technology",
                          userName: "TheWolf",
                          textColor: "#FFFFFF",
                        },
                        creatorEmail: "jfoxworth@cadwolf.com",
                        creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
                        created_at: "1672798519",
                        type: "TAG",
                        followers: 0,
                        updated_at: 0,
                        SK: "",
                        parent_tag_id: "0",
                        PK: "",
                        id: "01GNX8ZGFM2P9BZX6DTA610ZF6",
                        articlesList: [],
                        embeds: 0,
                      },
                    ],
                    tagColor: "#239f31",
                    cumulatives: [],
                    description:
                      "This tag holds all information related to startups, incubators, accelerators, and similar organizations and events.",
                    articlesList: [],
                    tagName: "Startups",
                    userName: "TheWolf",
                    articleListLimit: 5,
                    textColor: "#FFFFFF",
                  },
                  creatorEmail: "jfoxworth@cadwolf.com",
                  creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
                  created_at: "1672975460",
                  cumulatives: [],
                  type: "TAG",
                  followers: 0,
                  tagTree: [],
                  updated_at: "1672975475",
                  SK: "TAG#01GP2HQ9PB9TDYDFNPVRHEM973",
                  parent_tag_id: "01GNX8ZGFM2P9BZX6DTA610ZF6",
                  PK: "PTAG#01GNX8ZGFM2P9BZX6DTA610ZF6",
                  id: "01GP2HQ9PB9TDYDFNPVRHEM973",
                  articlesList: [],
                  embeds: 0,
                },
              ],
              tagColor: "#a4193b",
              cumulatives: [],
              description:
                '"Incubators" or "accelerators" are organizations that fund and/or assist startup companies. Tags are present for the larger accelerators as well as information relating to overall startups.',
              articlesList: [],
              tagName: "Incubators / Accelerators",
              userName: "TheWolf",
              articleListLimit: 5,
              textColor: "#FFFFFF",
            },
            creatorEmail: "jfoxworth@cadwolf.com",
            creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
            created_at: "1672975876",
            cumulatives: [],
            type: "TAG",
            followers: 0,
            tagTree: [],
            updated_at: "1675791013",
            SK: "TAG#01GP2J40RYCC9KW416BSPH8X88",
            parent_tag_id: "01GP2HQ9PB9TDYDFNPVRHEM973",
            PK: "PTAG#01GP2HQ9PB9TDYDFNPVRHEM973",
            id: "01GP2J40RYCC9KW416BSPH8X88",
            articlesList: [],
            embeds: 0,
          },
        ],
        tagColor: "#f26625",
        cumulatives: [],
        description:
          "YCombinator is a startup factory/incubator that has batches twice a year where it funds numerous companies with a small round and provides mentorship and networking. This tag contains batch information as well as data related to individual companies.",
        articlesList: [],
        tagName: "YCombinator",
        userName: "TheWolf",
        articleListLimit: 5,
        textColor: "#FFFFFF",
      },
      embeds: 0,
      SK: "TAG#01GP2JCWM8CDN6GV06BAEJTNBY",
      PK: "PTAG#01GP2J40RYCC9KW416BSPH8X88",
      id: "01GP2JCWM8CDN6GV06BAEJTNBY",
      creatorId: null,
      parent_tag_id: "01GP2J40RYCC9KW416BSPH8X88",
      type: "TAG",
    },
    size: "small",
  },
};

export const YCombinator = {
  args: {
    tag: {
      created_at: "1672976167",
      imports: 0,
      followers: 0,
      creatorEmail: "jfoxworth@cadwolf.com",
      updated_at: "1676841099",
      data: {
        userPoints: [],
        tagTree: [
          {
            imports: 0,
            data: {
              userPoints: [],
              tagTree: [],
              tagColor: "#898989",
              articlesListLimit: 5,
              cumulatives: [],
              description:
                "This tag includes stories related to technology, but not science. This can be crypto information, new apple devices, AI, new software advancements, and similar items.",
              articlesList: [],
              tagName: "Technology",
              userName: "TheWolf",
              textColor: "#FFFFFF",
            },
            creatorEmail: "jfoxworth@cadwolf.com",
            creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
            created_at: "1672798519",
            type: "TAG",
            followers: 0,
            updated_at: 0,
            SK: "",
            parent_tag_id: "0",
            PK: "",
            id: "01GNX8ZGFM2P9BZX6DTA610ZF6",
            articlesList: [],
            embeds: 0,
          },
          {
            imports: 0,
            data: {
              userPoints: [],
              tagTree: [
                {
                  imports: 0,
                  data: {
                    userPoints: [],
                    tagTree: [],
                    tagColor: "#898989",
                    articlesListLimit: 5,
                    cumulatives: [],
                    description:
                      "This tag includes stories related to technology, but not science. This can be crypto information, new apple devices, AI, new software advancements, and similar items.",
                    articlesList: [],
                    tagName: "Technology",
                    userName: "TheWolf",
                    textColor: "#FFFFFF",
                  },
                  creatorEmail: "jfoxworth@cadwolf.com",
                  creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
                  created_at: "1672798519",
                  type: "TAG",
                  followers: 0,
                  updated_at: 0,
                  SK: "",
                  parent_tag_id: "0",
                  PK: "",
                  id: "01GNX8ZGFM2P9BZX6DTA610ZF6",
                  articlesList: [],
                  embeds: 0,
                },
              ],
              tagColor: "#239f31",
              cumulatives: [],
              description:
                "This tag holds all information related to startups, incubators, accelerators, and similar organizations and events.",
              articlesList: [],
              tagName: "Startups",
              userName: "TheWolf",
              articleListLimit: 5,
              textColor: "#FFFFFF",
            },
            creatorEmail: "jfoxworth@cadwolf.com",
            creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
            created_at: "1672975460",
            cumulatives: [],
            type: "TAG",
            followers: 0,
            tagTree: [],
            updated_at: "1672975475",
            SK: "TAG#01GP2HQ9PB9TDYDFNPVRHEM973",
            parent_tag_id: "01GNX8ZGFM2P9BZX6DTA610ZF6",
            PK: "PTAG#01GNX8ZGFM2P9BZX6DTA610ZF6",
            id: "01GP2HQ9PB9TDYDFNPVRHEM973",
            articlesList: [],
            embeds: 0,
          },
          {
            imports: 0,
            data: {
              userPoints: [],
              tagTree: [
                {
                  imports: 0,
                  data: {
                    userPoints: [],
                    tagTree: [],
                    tagColor: "#898989",
                    articlesListLimit: 5,
                    cumulatives: [],
                    description:
                      "This tag includes stories related to technology, but not science. This can be crypto information, new apple devices, AI, new software advancements, and similar items.",
                    articlesList: [],
                    tagName: "Technology",
                    userName: "TheWolf",
                    textColor: "#FFFFFF",
                  },
                  creatorEmail: "jfoxworth@cadwolf.com",
                  creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
                  created_at: "1672798519",
                  type: "TAG",
                  followers: 0,
                  updated_at: 0,
                  SK: "",
                  parent_tag_id: "0",
                  PK: "",
                  id: "01GNX8ZGFM2P9BZX6DTA610ZF6",
                  articlesList: [],
                  embeds: 0,
                },
                {
                  imports: 0,
                  data: {
                    userPoints: [],
                    tagTree: [
                      {
                        imports: 0,
                        data: {
                          userPoints: [],
                          tagTree: [],
                          tagColor: "#898989",
                          articlesListLimit: 5,
                          cumulatives: [],
                          description:
                            "This tag includes stories related to technology, but not science. This can be crypto information, new apple devices, AI, new software advancements, and similar items.",
                          articlesList: [],
                          tagName: "Technology",
                          userName: "TheWolf",
                          textColor: "#FFFFFF",
                        },
                        creatorEmail: "jfoxworth@cadwolf.com",
                        creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
                        created_at: "1672798519",
                        type: "TAG",
                        followers: 0,
                        updated_at: 0,
                        SK: "",
                        parent_tag_id: "0",
                        PK: "",
                        id: "01GNX8ZGFM2P9BZX6DTA610ZF6",
                        articlesList: [],
                        embeds: 0,
                      },
                    ],
                    tagColor: "#239f31",
                    cumulatives: [],
                    description:
                      "This tag holds all information related to startups, incubators, accelerators, and similar organizations and events.",
                    articlesList: [],
                    tagName: "Startups",
                    userName: "TheWolf",
                    articleListLimit: 5,
                    textColor: "#FFFFFF",
                  },
                  creatorEmail: "jfoxworth@cadwolf.com",
                  creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
                  created_at: "1672975460",
                  cumulatives: [],
                  type: "TAG",
                  followers: 0,
                  tagTree: [],
                  updated_at: "1672975475",
                  SK: "TAG#01GP2HQ9PB9TDYDFNPVRHEM973",
                  parent_tag_id: "01GNX8ZGFM2P9BZX6DTA610ZF6",
                  PK: "PTAG#01GNX8ZGFM2P9BZX6DTA610ZF6",
                  id: "01GP2HQ9PB9TDYDFNPVRHEM973",
                  articlesList: [],
                  embeds: 0,
                },
              ],
              tagColor: "#a4193b",
              cumulatives: [],
              description:
                '"Incubators" or "accelerators" are organizations that fund and/or assist startup companies. Tags are present for the larger accelerators as well as information relating to overall startups.',
              articlesList: [],
              tagName: "Incubators / Accelerators",
              userName: "TheWolf",
              articleListLimit: 5,
              textColor: "#FFFFFF",
            },
            creatorEmail: "jfoxworth@cadwolf.com",
            creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
            created_at: "1672975876",
            cumulatives: [],
            type: "TAG",
            followers: 0,
            tagTree: [],
            updated_at: "1675791013",
            SK: "TAG#01GP2J40RYCC9KW416BSPH8X88",
            parent_tag_id: "01GP2HQ9PB9TDYDFNPVRHEM973",
            PK: "PTAG#01GP2HQ9PB9TDYDFNPVRHEM973",
            id: "01GP2J40RYCC9KW416BSPH8X88",
            articlesList: [],
            embeds: 0,
          },
        ],
        tagColor: "#f26625",
        cumulatives: [],
        description:
          "YCombinator is a startup factory/incubator that has batches twice a year where it funds numerous companies with a small round and provides mentorship and networking. This tag contains batch information as well as data related to individual companies.",
        articlesList: [],
        tagName: "YCombinator",
        userName: "TheWolf",
        articleListLimit: 5,
        textColor: "#FFFFFF",
      },
      embeds: 0,
      SK: "TAG#01GP2JCWM8CDN6GV06BAEJTNBY",
      PK: "PTAG#01GP2J40RYCC9KW416BSPH8X88",
      id: "01GP2JCWM8CDN6GV06BAEJTNBY",
      creatorId: null,
      parent_tag_id: "01GP2J40RYCC9KW416BSPH8X88",
      type: "TAG",
    },
  },
};
