import TagList from "./index.jsx";

const tagList = [
  {
    created_at: "1671829858",
    imports: 0,
    followers: 0,
    creatorEmail: "jfoxworth@cadwolf.com",
    updated_at: "1672891755",
    data: {
      tagTree: [],
      tagColor: "#d00b3c",
      childTags: 0,
      cumulatives: [],
      description:
        "This holds everything related to sports. At the first level, is a tag for each sport - NFL, MLB, NBA, etc. Beneath that is a tag for every team or franchise as well as a general news category. Individual players, events, scandals, etc are then placed within the appropriate category.",
      articleLimit: 10,
      articlesList: [],
      tagName: "Sports",
      type: "thing",
      userName: "TheWolf",
      textColor: "#FFFFFF",
    },
    embeds: 0,
    userid: "01GN5EG33E1HGFV4TYRKF9SV1R",
    SK: "TAG#01GN0D6AF0SKMX9VX87YKSGPS7",
    PK: "PTAG#0",
    id: "01GN0D6AF0SKMX9VX87YKSGPS7",
    creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
    parent_tag_id: "0",
    type: "TAG",
  },
  {
    created_at: "1672797252",
    imports: 0,
    followers: 0,
    creatorEmail: "jfoxworth@cadwolf.com",
    updated_at: "1672890638",
    data: {
      userPoints: [],
      tagTree: [],
      tagColor: "#cbd813",
      articlesListLimit: 5,
      cumulatives: [],
      description:
        "This tag contains a tag for elections, for the House, the Senate, the Presidency, and other items. Within that, there is a tag for each representative, and then a tag for each issue or scandal for a representative.",
      articlesList: [],
      tagName: "US Politics",
      userName: "TheWolf",
      textColor: "#FFFFFF",
    },
    embeds: 0,
    SK: "TAG#01GNX7RV1Z0FC48396Z4AXY8NW",
    PK: "PTAG#0",
    id: "01GNX7RV1Z0FC48396Z4AXY8NW",
    creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
    parent_tag_id: "0",
    type: "TAG",
  },
  {
    created_at: "1672797379",
    imports: 0,
    followers: 0,
    creatorEmail: "jfoxworth@cadwolf.com",
    updated_at: "1672890727",
    data: {
      userPoints: [],
      tagTree: [],
      tagColor: "#0d0c0c",
      articlesListLimit: 5,
      cumulatives: [],
      description:
        "This tag contains a separate tag for each nation. Within those tags are relevant child tags for the legislative bodies and then child tags for any representative, issue, or other subject.",
      articlesList: [],
      tagName: "World Politics",
      userName: "TheWolf",
      textColor: "#FFFFFF",
    },
    embeds: 0,
    SK: "TAG#01GNX7WPJWE68WR7GSW2Q57H82",
    PK: "PTAG#0",
    id: "01GNX7WPJWE68WR7GSW2Q57H82",
    creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
    parent_tag_id: "0",
    type: "TAG",
  },
  {
    created_at: "1672797461",
    imports: 0,
    followers: 0,
    creatorEmail: "jfoxworth@cadwolf.com",
    updated_at: "1672890744",
    data: {
      userPoints: [],
      tagTree: [],
      tagColor: "#1e850a",
      articlesListLimit: 5,
      cumulatives: [],
      description:
        "This tag holds all information related to economics. It has child tags for a number of subjects and people. ",
      articlesList: [],
      tagName: "Economics",
      userName: "TheWolf",
      textColor: "#FFFFFF",
    },
    embeds: 0,
    SK: "TAG#01GNX7Z6WTY9RW6FKJNQBSQZSA",
    PK: "PTAG#0",
    id: "01GNX7Z6WTY9RW6FKJNQBSQZSA",
    creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
    parent_tag_id: "0",
    type: "TAG",
  },
  {
    created_at: "1672798174",
    imports: 0,
    followers: 0,
    creatorEmail: "jfoxworth@cadwolf.com",
    updated_at: "1672890768",
    data: {
      userPoints: [],
      tagTree: [],
      tagColor: "#1bdacd",
      articlesListLimit: 5,
      cumulatives: [],
      description:
        "Within this tag is a child for each nation. These tags are then broken down further into states, provinces, etc and then into cities. Stories for those tags are then placed into appropriate tags based on subject.",
      articlesList: [],
      tagName: "Location based news",
      userName: "TheWolf",
      textColor: "#FFFFFF",
    },
    embeds: 0,
    SK: "TAG#01GNX8MYTGJ2SM8SAJYBZS2DT3",
    PK: "PTAG#0",
    id: "01GNX8MYTGJ2SM8SAJYBZS2DT3",
    creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
    parent_tag_id: "0",
    type: "TAG",
  },
  {
    created_at: "1672798307",
    imports: 0,
    followers: 0,
    creatorEmail: "jfoxworth@cadwolf.com",
    updated_at: "1672890837",
    data: {
      userPoints: [],
      tagTree: [],
      tagColor: "#983a3a",
      articlesListLimit: 5,
      cumulatives: [],
      description:
        "This tag is first broken down into categories such as music, film, internet, and books. Each of those tags then holds a number of child tags related to specific people, subjects, and events.  ",
      articlesList: [],
      tagName: "Entertainment",
      userName: "TheWolf",
      textColor: "#FFFFFF",
    },
    embeds: 0,
    SK: "TAG#01GNX8S1BP5XBG3QD96JWRRTWC",
    PK: "PTAG#0",
    id: "01GNX8S1BP5XBG3QD96JWRRTWC",
    creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
    parent_tag_id: "0",
    type: "TAG",
  },
  {
    created_at: "1672798447",
    imports: 0,
    followers: 0,
    creatorEmail: "jfoxworth@cadwolf.com",
    updated_at: "1672890885",
    data: {
      userPoints: [],
      tagTree: [],
      tagColor: "#1d23dd",
      articlesListLimit: 5,
      cumulatives: [],
      description:
        "All stories related to science and space exploration are held within this tag. This includes bureaucratic information relating to NASA and its' programs as well as international space programs. Any other stories related to science are also encompassed within this tag.",
      articlesList: [],
      tagName: "Space and Science",
      userName: "TheWolf",
      textColor: "#FFFFFF",
    },
    embeds: 0,
    SK: "TAG#01GNX8X9VCGA3XJ8AF6PNZ5X7W",
    PK: "PTAG#0",
    id: "01GNX8X9VCGA3XJ8AF6PNZ5X7W",
    creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
    parent_tag_id: "0",
    type: "TAG",
  },
  {
    created_at: "1672798519",
    imports: 0,
    followers: 0,
    creatorEmail: "jfoxworth@cadwolf.com",
    updated_at: "1675791013",
    data: {
      userPoints: [],
      tagTree: [],
      tagColor: "#898989",
      articlesListLimit: 5,
      cumulatives: [],
      description:
        "This tag includes stories related to technology, but not science. This can be crypto information, new apple devices, startups, AI, new software advancements, and similar items.",
      articlesList: [],
      tagName: "Technology",
      userName: "TheWolf",
      textColor: "#FFFFFF",
    },
    embeds: 0,
    SK: "TAG#01GNX8ZGFM2P9BZX6DTA610ZF6",
    PK: "PTAG#0",
    id: "01GNX8ZGFM2P9BZX6DTA610ZF6",
    creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
    parent_tag_id: "0",
    type: "TAG",
  },
  {
    created_at: "1672798597",
    imports: 0,
    followers: 0,
    creatorEmail: "jfoxworth@cadwolf.com",
    updated_at: "1672890914",
    data: {
      userPoints: [],
      tagTree: [],
      tagColor: "#ad12af",
      articlesListLimit: 5,
      cumulatives: [],
      description:
        "General health related stories are included within this tag, but also specific stories related to health care stories such as COVID.",
      articlesList: [],
      tagName: "Health and Medicine",
      userName: "TheWolf",
      textColor: "#FFFFFF",
    },
    embeds: 0,
    SK: "TAG#01GNX91W9J4SCBN5X19ZMZAK0M",
    PK: "PTAG#0",
    id: "01GNX91W9J4SCBN5X19ZMZAK0M",
    creatorId: "01GN5EG33E1HGFV4TYRKF9SV1R",
    parent_tag_id: "0",
    type: "TAG",
  },
];

// More on how to set up stories at: https://storybook.js.org/docs/react/writing-stories/introduction
export default {
  title: "Compound/TagList",
  component: TagList,
  args: {},
};

export const SampleList = {
  args: {
    tags: tagList,
  },
};
